routes/web.php
<?php

use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


use App\Http\Controllers\HieuController;
Route::get('/hieu', [HieuController::class, 'test']);

Route::view('/gau', 'gau');

use App\Http\Controllers\StudentController;
use App\Http\Controllers\ComicController;

Route::middleware(['check-login'])->group(function () {
    
Route::get('/student', [StudentController::class, 'index'])->name('StudentList');

Route::get('/student/create', [StudentController::class, 'create_student'])->name('CreateStudent');
Route::post('/student/save', [StudentController::class, 'save'])->name('SaveStudent');



Route::get('/student/show/{id}',[StudentController::class, 'show'])->name('ShowStudent');
Route::post('/student/edit', [StudentController::class, 'edit'])->name('UpdateStudent');

Route::get('/student/createajax', [StudentController::class, 'create_student_ajax'])->name('CreateStudentAjax');
Route::post('/student/savestudentajax', [StudentController::class, 'savestudentajax'])->name('SaveStudentAjax');

Route::get('/student/store', [StudentController::class, 'store_computer']);

Route::get('/student/computer', [StudentController::class, 'computer']);

Route::get('/comic/list', [ComicController::class, 'comic_list'])->name('ComicList');
Route::get('/comic/create', [ComicController::class, 'create'])->name('CreateComic');
Route::get('/comic/createajax', [ComicController::class, 'create_ajax'])->name('CreateComicAjax');
Route::post('/comic/savecomic',[ComicController::class, 'saveComic'])->name('SaveComic');
Route::post('/comic/savecomicajax',[ComicController::class, 'saveComicAjax'])->name('SaveComicAjax');
Route::get('/comic/delete/{id}',[ComicController::class, 'deleteComic'])->name('DeleteComic');
Route::get('/comic/deleteajax',[ComicController::class, 'deleteComicajax'])->name('DeleteComicAjax');
});
use App\Http\Controllers\UserController;

Route::middleware(['check-authenticated-user'])->group(function () {
Route::get('/login', [UserController::class, 'login'])->name('Login');
Route::post('/authlogin', [UserController::class, 'authlogin'])->name('AuthLogin');
	});

Route::get('/user/create', [UserController::class, 'CreateUser'])->name('CreateUser');
Route::post('/user/saveuser', [UserController::class, 'SaveUser'])->name('SaveUser');



Route::get('/logout', [UserController::class, 'logout'])->name('Logout');

Route::get('/{any}', function () {
    //return view('welcome');
})->middleware('check-comic');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;


use App\Models\User;

class UserController extends Controller
{
    public function CreateUser()
    {
    	return view('admin.user.create');
    }
    public function SaveUser(Request $request)
    {
    	if ($request->isMethod('post')) 
        {                
      	    $user = new User;
      	    $current_time = date("Y-m-d h:i:s");
      	    $user->name= $request->input('UserName');
	        $user->email= $request->input('UserEmail');
	        $user->password=Hash::make($request->input('UserPassword'));
	        $user->created_at=$current_time;
	        $user->updated_at=$current_time;         
	        $user->save();
	        return redirect()->route('CreateUser')->with('message', 'Add user successfully !')->with('status','success');    
    	}    	
    }
    public function login()
    {
    	return view('admin.login');
    }
    public function authlogin(Request $request)
    {
    	$credentials = $request->only('email', 'password');
    	if (Auth::attempt($credentials)) 

    	//if (Auth::attempt(['name' => $request->input('name'), 'password' => $request->input('password')])) 
    	{
            $request->session()->regenerate();

            return redirect()->route('StudentList');
        }
        return back()->withErrors([
            'email' => 'The provided credentials do not match our records.',
        ]);
    }

    public function logout(Request $request)
	{
    	Auth::logout();

    	$request->session()->invalidate();

    	$request->session()->regenerateToken();

   		 return redirect()->route('Login');
	}
}

app/View/Components/Alert.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Alert extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    
    public $message;
    public $status;
    public function __construct($message,$status)
    {
         $this->message = $message;
         $this->status = $status;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    { 
        switch ($this->status) {
        case "success":
            return view('components.alert_success');
            break;
        case "fail":
            return view('components.alert_fail');
            break;
        default:
            return view('components.alert_fail');
            break;
        }       
        
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.main')

@section('title', 'Create Users')

@section('headline', 'Create Users')

@section('content')

 <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-6">
          
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Create Users</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              
                 <form method="POST" action="{{route('SaveUser')}}">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="UserName">Name</label>
                    <input type="text" class="form-control" id="UserName" placeholder="Enter name" name="UserName">
                  </div>
                  <div class="form-group">
                    <label for="UserEmail">Email</label>
                    <input type="text" class="form-control" id="UserEmail" placeholder="Enter Email" name="UserEmail">
                  </div>
                  <div class="form-group">
                    <label for="UserPassword">Password</label>
                    <input type="password" class="form-control" id="UserPassword" placeholder="Enter Password" name="UserPassword">
                  </div>
                  
                          

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                   <button type="submit" id="AddUserBtn" name="AddUser" class="btn btn-primary">Add User</button>

                      @if(Session::has('message'))
                       <x-alert status="{{session('status')}}" message="{{session('message')}}"/>
                       
                      @endif

                </div>
              </form>

              {{explode('@', Route::getCurrentRoute()->getActionName())[0]}}
              <br>
              {{explode('@', Route::getCurrentRoute()->getActionName())[1]}}

            </div>

           

          </div>
          <!-- /.col-md-6 -->
       
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->

@endsection